### PR TITLE
add GUI calculator to the education_play_ground folder

### PR DESCRIPTION
**Pull request by mostafakavand**

### CODE REVIEW

**Comment by mostafakavand** [comment]
A beautiful experience

**Comment by MohammadJavadTabari** [comment]
hi, when you gonna send  PR(pull request)
make sure you delete test file
i do it for you this time.
but next time take care of extra files
like:
assas.xlsx   !!!!
sfwesfj.py  !!!!

**Comment by MohammadJavadTabari** [comment]
> hi, when you gonna send PR(pull request) make sure you delete test file i do it for you this time. but next time take care of extra files like: assas.xlsx !!!! sfwesfj.py !!!!



> A beautiful experience

check my comment

**Review by MohammadJavadTabari — APPROVED** [review]
this closes #24

**Comment by mostafakavand** [comment]
Sorry, I pulled these files by mistake

**Comment by MohammadJavadTabari** [comment]
> Sorry, I pulled these files by mistake

you "pushed" it, not pull !
that's ok man. you done a nice job

**Comment by mostafakavand** [comment]
Yes you are right.  It will take me a while to get used to these terms.  "So the process is like this: I push and you pull"

**Pull request merged**
