### PR TITLE
Add blohg project

### PR DESCRIPTION
**Pull request by Mohammadreza-Rokni**
hi @BamdadTabari 
please check my blog project
Thanks.

### CODE REVIEW

**Comment by BamdadTabari** [comment]
zero:
I wanna make sure that I like your job and professional personality. so I will talk to you so much.
first; 
you are good at your job, and I admire you for this.
second:
now that you learn how to build web applications with python and Django, it's time to get deeper.
and have a better look at concepts.
third:
let's go deeper in the next comment

**Comment by BamdadTabari** [comment]
ok get deeper;
268 file change? ( half of them are in __pycache__)  =>>> find a way to make them clear. 
python and Django build so many files during building and running; I want you to search about that, =>>> what are these files? how can we handle them in our repositories? should we clean them? 
also, there are so many js files, are you using all of them in the project?
you used both bootstrap and material together why?
I never see anyone do this. it's not a crime but, I want a reason for that.

these are for now maybe I see more in the next round.

**Comment by BamdadTabari** [comment]
@Mohammadreza-Rokni  any change? 
do you fix the last comment? 
are you need help

**Comment by Mohammadreza-Rokni** [comment]
@BamdadTabari 
I will apply the changes you said in the next day or two, because more than 95% of it has been developed and there is nothing left to complete, I will put it aside for now and watch side trainings.

**Comment by BamdadTabari** [comment]
> @BamdadTabari I will apply the changes you said in the next day or two, because more than 95% of it has been developed and there is nothing left to complete, I will put it aside for now and watch side trainings.

hurry up dayi. new projects are comming

**Comment by Mohammadreza-Rokni** [comment]
Regarding the use of Bootstrap and Material together,because i used a ready template there can be several reasons for this. It could be that the project requires certain components or features that are provided by both frameworks. Alternatively, the project may have been started with one framework and then switched to the other, resulting in a mix of code from both frameworks. However,I realized that it is generally advisable to stick to one framework to ensure consistency and ease of maintenance.

**Comment by BamdadTabari** [comment]
> Regarding the use of Bootstrap and Material together,because i used a ready template there can be several reasons for this. It could be that the project requires certain components or features that are provided by both frameworks. Alternatively, the project may have been started with one framework and then switched to the other, resulting in a mix of code from both frameworks. However,I realized that it is generally advisable to stick to one framework to ensure consistency and ease of maintenance.

you can use bootstrap. min.cs   & botosrap.min.js. then you add 2 files instead of 268. but here is a playground. no need to change. everything is fine.  
can you build a blog project with Django in Dayana Repoes? if yes?! do your best. 
if you have permission errors to build a repo, just call me here. i will give you access

**Pull request merged**
