### PR TITLE
Adding QR-code practice file to the playground 

### PR DESCRIPTION
**Pull request by HosseinChoopani**
I know there are some extra and messy commits

### CODE REVIEW

**Review by MohammadJavadTabari — COMMENTED** [review]
every thing is fine but
there is a bug , a big bug, very big bug
why man? why you write your code in Jupyter.
this should be readable for students man :octocat: 
this file is ok. but please add " .py " file too. thanks man

**Comment by HosseinChoopani** [comment]
> every thing is fine but there is a bug , a big bug, very big bug why man? why you write your code in Jupyter. this should be readable for students man :octocat: this file is ok. but please add " .py " file too. thanks man

I conducted a little experiment on QR codes and so used Jupiter notebook for showing results and generated QR codes. it is impossible to do these without Jupyter.
why it is not readable for students? it is kind of more readable and understandable.
However, I will add the .py file.
thanks and best regards

**Comment by MohammadJavadTabari** [comment]
> > every thing is fine but there is a bug , a big bug, very big bug why man? why you write your code in Jupyter. this should be readable for students man :octocat: this file is ok. but please add " .py " file too. thanks man
> 
> I conducted a little experiment on QR codes and so used Jupiter notebook for showing results and generated QR codes. it is impossible to do these without Jupyter. why it is not readable for students? it is kind of more readable and understandable. However, I will add the .py file. thanks and best regards

i got your point.
thanks man

**Review by MohammadJavadTabari — APPROVED** [review]
well done

**Pull request merged**
